### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by yahya-mohammed07** [gmpetrov/openai-chatgpt#1]
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/mnt/c/Users/DELL/AppData/Roaming/npm/node_modules/openai-chatgpt/dist/cli.js:10:31)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by yahya-mohammed07** [comment]
can you also add more usage details?

**Comment by gmpetrov** [comment]
Hi, what's your nodejs version?

**Comment by yahya-mohammed07** [comment]
v12.22.9, WSL2

**Comment by gmpetrov** [comment]
Your nodejs version is quite old. Can you try again with at least v18?

**Comment by yahya-mohammed07** [comment]
sure,  gonna update and see what happens
