### ISSUE TITLE
Error: Invalid environment: global fetch not defined

### ISSUE THREAD

**Issue by Flashtheorie** [gmpetrov/openai-chatgpt#2]
`[ERROR] Error: Invalid environment: global fetch not defined
    at file:///usr/local/lib/node_modules/openai-chatgpt/node_modules/chatgpt/build/index.js:15:9
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async sendMessage (/usr/local/lib/node_modules/openai-chatgpt/dist/utils/send-message.js:11:32)
    at async /usr/local/lib/node_modules/openai-chatgpt/dist/components/App.js:87:25
`

**Comment by gmpetrov** [comment]
It's because your nodejs version is older than v18. 
I just released a fix (v0.0.7. ) for older node versions

Run: npm install -g openai-chatgpt@latest

**Comment by Flashtheorie** [comment]
Lovely, thank you
